# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField(null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9999)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=9999, null=True)),
            ],
        ),
    ]
