# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20170217_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(blank=True, default='foto', max_length=40, null=True),
        ),
    ]
