# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 20:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0008_producto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='administradores',
            field=models.ManyToManyField(blank=True, related_name='administradores_producto', to=settings.AUTH_USER_MODEL),
        ),
    ]
