# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_producto_administradores'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='apellido',
            field=models.CharField(default='Zapata', max_length=40),
            preserve_default=False,
        ),
    ]
