# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 19:54
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import productos.models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_producto_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='media',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/Users/chris/Documents/Proyectos/git_dm/digital_market/django_dm/protected'), upload_to=productos.models.download_media_location),
        ),
    ]
