# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import productos.models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_auto_20170404_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=productos.models.download_media_location),
        ),
    ]
